; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

; https://community.platformio.org/t/esp32-s3-zero-does-not-work-on-platformio/40297/10?u=unsignedarduino
; https://github.com/sivar2311/ESP32-S3-PlatformIO-Flash-and-PSRAM-configurations
[env:esp32-s3-devkitc-1]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = esp32-s3-devkitc-1
framework = arduino
board_build.arduino.memory_type = qio_qspi
board_build.flash_mode = qio
board_build.psram_type = qio
board_upload.flash_size = 4MB
board_upload.maximum_size = 4194304
board_build.partitions = huge_app.csv
build_flags = -I include
              -DARDUINO_USB_CDC_ON_BOOT=1
              -DBOARD_HAS_PSRAM
              ; spec for matter
              -std=gnu++17
board_build.filesystem = littlefs
monitor_speed = 115200
upload_speed = 115200
monitor_filters = esp32_exception_decoder
; MAKE SURE TO INCLUDE THESE IF YOU ARE CHANGING ESP32
lib_deps =
    fastled/FastLED
    madhephaestus/ESP32Servo
;spec for matter
build_unflags = -std=gnu++11
    
